services:
  postgres:
    image: postgres:latest
    container_name: postgres-dotnet
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-dotnet

  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        - stage=dev
        - port=5001
    container_name: lt-docker-netcore-app
    environment:
      - PHASE_API_KEY=${PHASE_API_KEY}
      - POSTGRES_SECRET_NAME=${PHASE_APP_ID}
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - app-dotnet

networks:
  app-dotnet:
    driver: bridge